[selene]
base = "lua51"
name = "vim"

[vim]
any = true

[describe]
args = [{ type = "string" }, { type = "function" }]

[it]
args = [{ type = "string" }, { type = "function" }]

[before_each]
args = [{ type = "function" }]

[after_each]
args = [{ type = "function" }]
