local T = vim.keycode
local leader = T '<leader>'

--- Search term for project-wide substitute (blank input = same term RipGrep used).
---@param term string|nil
---@return string|nil
local function effective_search_term(term)
  if term == nil then
    return nil
  end
  if term ~= '' then
    return term
  end
  local qf_term = vim.g.qf_search_term
  if type(qf_term) == 'string' and qf_term ~= '' then
    return vim.trim(qf_term)
  end
  return vim.fn.expand '<cword>'
end

---@param term string
---@param literal boolean
---@return string
local function substitute_pattern(term, literal)
  if literal then
    return '\\V' .. vim.fn.escape(term, '\\')
  end
  return vim.fn.escape(term, '?&/\\')
end

---@param term string
---@return string
local function substitute_replacement(term)
  return vim.fn.escape(term, '?&/\\~')
end

---@return string dir
---@return string file
local function shada_location()
  local dir = vim.fn.stdpath 'state' .. '/shada'
  local name = 'main'
  for token in vim.o.shada:gmatch '[^,]+' do
    if token:sub(1, 1) == 'n' and #token > 1 then
      name = token:sub(2)
    end
  end
  return dir, dir .. '/' .. name .. '.shada'
end

local find_in_project = function(opts)
  opts = opts or {
    literal_search = true,
    callback = function() end,
    noautocmd = false,
  }
  local bang = opts.literal_search and '' or '!'
  local noautocmd_str = opts.noautocmd and 'noautocmd ' or ''
  vim.ui.input({ prompt = 'Enter search term (blank for word under cursor)? ' }, function(search_term)
    if search_term == nil then
      return
    end
    local original_search_term = search_term
    local grep_arg = search_term ~= '' and (' ' .. search_term) or ''

    vim.cmd(noautocmd_str .. 'RipGrepCWORD' .. bang .. grep_arg)
    opts.callback(original_search_term)
  end)
end

local search_and_replace = function(literal_search)
  find_in_project {
    literal_search = literal_search,
    callback = function(search_term)
      search_term = effective_search_term(search_term)
      if not search_term or search_term == '' then
        vim.notify('No search term.', vim.log.levels.WARN, { title = 'Search and Replace' })
        return
      end

      vim.ui.input({ prompt = 'Enter Replace term? ' }, function(replace_term)
        if replace_term == nil then
          vim.notify('Canceled.', vim.log.levels.INFO, { title = 'Search and Replace' })
          return
        end
        vim.ui.input({
          prompt = 'Enter flags (g=global, c=confirm, i=case insensitive, e=ignore errors, n=only count)? ',
          default = 'gce',
        }, function(flags)
          if flags == nil then
            vim.notify('Canceled.', vim.log.levels.INFO, { title = 'Search and Replace' })
            return
          end
          local pattern = substitute_pattern(search_term, literal_search)
          local replacement = substitute_replacement(replace_term)
          vim.cmd(string.format('silent noautocmd cdo %%s?%s?%s?%s', pattern, replacement, flags))
        end)
      end)
    end,
    noautocmd = true,
  }
end

return {
  ['[Search] Find in pwd (literal search) (<C-f>)'] = function()
    find_in_project { literal_search = true }
  end,
  ['[Search] Find in pwd (regex search) (<C-f>)'] = function()
    find_in_project { literal_search = false }
  end,
  ['[Search] Search and Replace in cwd (literal search)'] = function()
    search_and_replace(true)
  end,
  ['[Search] Search and Replace in cwd (regex search)'] = function()
    search_and_replace(false)
  end,
  ['[Search] Replace word under cursor (<leader>r)'] = function()
    vim.fn.feedkeys(leader .. 'r')
  end,
  ['[Edit] Select all (vae / <leader>sa)'] = function()
    vim.cmd [[normal! ggVG]]
  end,
  ['[Edit] Indent block forward (<leader>gt)'] = function()
    vim.cmd [[normal! v%koj$>]]
  end,
  ['[Folds] Open all folds (<leader>fo | zR)'] = function()
    vim.cmd 'normal! zR'
  end,
  ['[Folds] Open fold (<leader>ff | za)'] = function()
    vim.cmd 'normal! za'
  end,
  ['[Folds] Open all folds folds under the cursor (level fold) (<leader>fl | zazczA)'] = function()
    vim.cmd 'normal! zazczA'
  end,
  ['[Folds] Close all folds (<leader>fc | zM)'] = function()
    vim.cmd 'normal! zM'
  end,
  ['[Terraform] Remove terragrunt files'] = function()
    local scan_dir = require 'plenary.scandir'
    local terraform_repo = require('user.git').get_toplevel_sync()
    scan_dir.scan_dir(terraform_repo, {
      add_dirs = false,
      respect_gitignore = false,
      search_pattern = '.*%.tf',
      on_insert = function(entry)
        local first_line = vim.fn.readfile(entry)[1]
        if first_line and first_line:match 'Generated by Terragrunt' then
          vim.notify('Deleting file: ' .. entry)
          vim.fn.delete(entry)
        end
      end,
    })
  end,
  ['[Terraform] leave "will be" on plan'] = function()
    vim.cmd [[
      v? will be ?d
      %s?\v^\s*#\s*(.*) will be (.*)?\1 \2?
    ]]
    -- set q register to -target
    vim.fn.setreg('q', [[yss'I-target=A \j]])
    vim.notify('Macro q set to -target', vim.log.levels.INFO, { title = 'Terraform' })
  end,
  ['[Format] Basic groovy format'] = function()
    vim.cmd.BasicGroovyFormat()
  end,
  ['[Misc] Where am I?'] = function()
    vim.cmd.Whereami()
  end,
  ['[Lua] Autocommand to reload the lua file nvim'] = function()
    if vim.api.nvim_get_option_value('filetype', { buf = 0 }) ~= 'lua' then
      ---@diagnostic disable-next-line: param-type-mismatch
      vim.notify('Filetype is not lua!', vim.log.levels.ERROR, { title = '🖥️' })
    end

    local text = [[
--# selene: allow(undefined_variable)
-- Reload the file when it changes on disk
local group = vim.api.nvim_create_augroup("ReloadModule", {clear = true})
vim.api.nvim_create_autocmd("BufWritePost", {
  buffer = 0,
  group = group,
  callback = function()
    vim.cmd("luafile %")
    vim.notify("Module reloaded")
  end,
})

vim.keymap.set('n', 'bla', function()
  vim.notify('hello!')
end)
    ]]
    -- prepend those lines to the beginning of the file
    vim.api.nvim_buf_set_lines(0, 0, 0, false, vim.split(text, '\n'))
    vim.cmd.write()
    vim.cmd 'luafile %'
  end,
  ['[View] Center Focus (zz)'] = function()
    vim.fn.feedkeys 'zz'
  end,
  ['[View] Bottom Focus (zb)'] = function()
    vim.fn.feedkeys 'zb'
  end,
  ['[View] Top Focus (zt)'] = function()
    vim.fn.feedkeys 'zt'
  end,
  ['[Macro] Record Macro (q{letter})'] = function()
    vim.ui.input({ prompt = 'Macro letter❯ ' }, function(macro_letter)
      if not macro_letter then
        macro_letter = 'q'
      end
      vim.fn.feedkeys('q' .. macro_letter)
      vim.notify('Recording macro ' .. macro_letter .. ' (hit q when finished)', vim.log.levels.INFO, { title = 'Macro' })
      vim.notify('You can repeat this macro with @' .. macro_letter, vim.log.levels.INFO, { title = 'Macro' })
    end)
  end,
  ['[Macro] Repeat Macro (@{letter} / Q)'] = function()
    vim.ui.input({ prompt = 'Macro letter❯ ' }, function(macro_letter)
      if not macro_letter then
        macro_letter = 'q'
      end
      vim.ui.input({ prompt = 'Enter how many times (leave blank for once)❯ ' }, function(macro_times)
        if not macro_times then
          macro_times = ''
        end
        vim.fn.feedkeys(macro_times .. '@' .. macro_letter)
      end)
    end)
  end,
  ['[File] Save current buffer as temp'] = function()
    local ft = vim.api.nvim_get_option_value('filetype', { buf = 0 })
    if ft == '' then
      vim.ui.select(vim.fn.getcompletion('', 'filetype'), { prompt = 'Filetype❯ ' }, function(selected)
        if not selected then
          vim.notify('Canceled.', vim.log.levels.INFO, { title = 'Save as temp' })
          return
        end
        vim.cmd('set filetype=' .. selected)
        -- save with the filetype extension
        vim.cmd('write ' .. vim.fn.tempname() .. '.' .. selected)
        vim.cmd 'edit'
      end)
    else
      vim.cmd('write ' .. vim.fn.tempname() .. '.' .. ft)
      vim.cmd 'edit'
    end
  end,
  ['[Search] Find files (<C-p>)'] = function()
    vim.cmd 'FzfLua files'
  end,
  ['[Search] Find buffers (<C-b>)'] = function()
    vim.cmd 'FzfLua buffers'
  end,
  ['[File] Open Nvim Tree File Browser (<leader>o)'] = function()
    local api = require 'nvim-tree.api'
    api.tree.toggle()
  end,
  ['[Misc] Close all notifications (<leader>x)'] = function()
    require('notify').dismiss { pending = true, silent = true }
  end,
  ['[Misc] Fix corrupted ShaDa file'] = function()
    local title = 'ShaDa'
    local dir, shada_file = shada_location()

    local removed_tmp = 0
    for _, path in ipairs(vim.fn.glob(dir .. '/*.tmp.*', false, true)) do
      if vim.fn.delete(path) == 0 then
        removed_tmp = removed_tmp + 1
      end
    end

    if vim.fn.filereadable(shada_file) ~= 1 then
      vim.cmd 'wshada'
      vim.notify(('Wrote new ShaDa file (none existed). Removed %d stale temp file(s).'):format(removed_tmp), vim.log.levels.INFO, { title = title })
      return
    end

    local backup = shada_file .. '.broken.' .. os.date '%Y%m%d-%H%M%S'
    if vim.fn.rename(shada_file, backup) ~= 0 then
      vim.notify('Could not move corrupt ShaDa file: ' .. shada_file, vim.log.levels.ERROR, { title = title })
      return
    end

    local ok = pcall(vim.cmd, 'silent! rshada! ' .. vim.fn.fnameescape(backup))
    vim.cmd 'wshada'

    local msg
    if ok then
      msg = ('Repaired ShaDa (salvaged what could be read). Backup: %s'):format(backup)
      if removed_tmp > 0 then
        msg = msg .. ('. Removed %d stale temp file(s).'):format(removed_tmp)
      end
      vim.notify(msg, vim.log.levels.INFO, { title = title })
    else
      msg = ('ShaDa reset (history lost). Corrupt backup: %s'):format(backup)
      if removed_tmp > 0 then
        msg = msg .. ('. Removed %d stale temp file(s).'):format(removed_tmp)
      end
      vim.notify(msg, vim.log.levels.WARN, { title = title })
    end
  end,
  ['[Misc] Quit all (<leader>qq)'] = function()
    vim.cmd.qall()
  end,
  ['[Edit] Paste from clipboard (cv)'] = function()
    vim.fn.feedkeys 'cv'
  end,
  ['[Edit] Copy entire file to clipboard (Y)'] = function()
    vim.fn.feedkeys 'Y'
  end,
  ['[Edit] Convert \\n to new lines (<leader><cr>)'] = function()
    vim.fn.feedkeys(leader .. T '<cr>')
  end,
  ['[Edit] Move line down (-)'] = function()
    vim.fn.feedkeys '-'
  end,
  ['[Edit] Move line up (_)'] = function()
    vim.fn.feedkeys '_'
  end,
  ['[View] Toggle words wrapping (<leader>ww)'] = function()
    vim.o.wrap = not vim.o.wrap
  end,
  ['[File] Copy full file path to clipboard (<leader>cfa)'] = function()
    vim.fn.feedkeys(leader .. 'cfa')
  end,
  ['[File] Copy relative file path to clipboard (<leader>cfp)'] = function()
    vim.fn.feedkeys(leader .. 'cfp')
  end,
  ['[File] Copy directory path to clipboard (<leader>cfd)'] = function()
    vim.fn.feedkeys(leader .. 'cfd')
  end,
  ['[File] Copy file name to clipboard (<leader>cfn)'] = function()
    vim.fn.feedkeys(leader .. 'cfn')
  end,
  ['[Edit] Split long bash line (<leader>\\'] = function()
    vim.fn.feedkeys(leader .. [[\]])
  end,
  ['[YAML] Yaml to Json (:Yaml2Json)'] = function()
    vim.cmd.Yaml2Json()
  end,
  ['[YAML] Add YAML Schema Modeline'] = function()
    require('yaml-companion').open_datree_crd_select()
  end,
  ['[JSON] Json to Yaml (:Json2Yaml)'] = function()
    vim.cmd.Json2Yaml()
  end,
  ['[JSON] Sort keys under a path (jq)'] = function()
    local title = 'Sort JSON'
    if vim.fn.executable 'jq' == 0 then
      vim.notify('jq not found in PATH.', vim.log.levels.WARN, { title = title })
      return
    end

    local bufnr = 0
    local src = table.concat(vim.api.nvim_buf_get_lines(bufnr, 0, -1, false), '\n')
    local enum = vim
      .system({
        'jq',
        '-c',
        'paths(type == "object" or type == "array") as $p | select((getpath($p) | length) > 1) | { p: $p, label: ("." + ($p | map(tostring) | join("."))) }',
      }, { stdin = src })
      :wait()
    if enum.code ~= 0 then
      vim.notify('Invalid JSON: ' .. (enum.stderr or ''), vim.log.levels.WARN, { title = title })
      return
    end

    local candidates = {}
    for line in vim.gsplit(enum.stdout, '\n', { trimempty = true }) do
      table.insert(candidates, vim.json.decode(line))
    end
    if #candidates == 0 then
      vim.notify('No container with multiple children to sort.', vim.log.levels.WARN, { title = title })
      return
    end

    vim.ui.select(candidates, {
      prompt = 'Sort under: ',
      format_item = function(item)
        return item.label
      end,
    }, function(choice)
      if not choice then
        return
      end
      local res = vim
        .system({
          'jq',
          '--argjson',
          'p',
          vim.json.encode(choice.p),
          'setpath($p; getpath($p) | if type == "object" then to_entries | sort_by(.key) | from_entries else sort end)',
        }, { stdin = src })
        :wait()
      if res.code ~= 0 then
        vim.notify('jq failed: ' .. (res.stderr or ''), vim.log.levels.WARN, { title = title })
        return
      end
      vim.api.nvim_buf_set_lines(bufnr, 0, -1, false, vim.split((res.stdout:gsub('\n$', '')), '\n'))
      vim.notify(('Sorted %s.'):format(choice.label), vim.log.levels.INFO, { title = title })
    end)
  end,
  ['[Editor] Change indent size (cii)'] = function()
    vim.fn.feedkeys 'cii'
  end,
  ['[Editor] Convert tabs to spaces (<leader>ct<SPC>)'] = function()
    local original_expandtab = vim.opt_global.expandtab:get()
    vim.opt.expandtab = true
    vim.cmd.retab()
    vim.opt.expandtab = original_expandtab
  end,
  ['[Diff] unsaved with saved file (<leader>ds)'] = function()
    vim.fn.feedkeys(leader .. 'ds')
  end,
  ['[File] Change directory to current file (<leader>.)'] = function()
    vim.fn.feedkeys(leader .. '.')
  end,
}
