---@return string dir
---@return string file
local function shada_location()
  local dir = vim.fn.stdpath 'state' .. '/shada'
  local name = 'main'
  for token in vim.o.shada:gmatch '[^,]+' do
    if token:sub(1, 1) == 'n' and #token > 1 then
      name = token:sub(2)
    end
  end
  return dir, dir .. '/' .. name .. '.shada'
end

return {
  ['[Terraform] Remove terragrunt files'] = function()
    local scan_dir = require 'plenary.scandir'
    local terraform_repo = require('user.git').get_toplevel_sync()
    scan_dir.scan_dir(terraform_repo, {
      add_dirs = false,
      respect_gitignore = false,
      search_pattern = '.*%.tf',
      on_insert = function(entry)
        local first_line = vim.fn.readfile(entry)[1]
        if first_line and first_line:match 'Generated by Terragrunt' then
          vim.notify('Deleting file: ' .. entry)
          vim.fn.delete(entry)
        end
      end,
    })
  end,
  ['[Terraform] leave "will be" on plan'] = function()
    vim.cmd [[
      v? will be ?d
      %s?\v^\s*#\s*(.*) will be (.*)?\1 \2?
    ]]
    -- set q register to -target
    vim.fn.setreg('q', [[yss'I-target=A \j]])
    vim.notify('Macro q set to -target', vim.log.levels.INFO, { title = 'Terraform' })
  end,
  ['[Lua] Autocommand to reload the lua file nvim'] = function()
    if vim.api.nvim_get_option_value('filetype', { buf = 0 }) ~= 'lua' then
      ---@diagnostic disable-next-line: param-type-mismatch
      vim.notify('Filetype is not lua!', vim.log.levels.ERROR, { title = '🖥️' })
    end

    local text = [[
--# selene: allow(undefined_variable)
-- Reload the file when it changes on disk
local group = vim.api.nvim_create_augroup("ReloadModule", {clear = true})
vim.api.nvim_create_autocmd("BufWritePost", {
  buffer = 0,
  group = group,
  callback = function()
    vim.cmd("luafile %")
    vim.notify("Module reloaded")
  end,
})

vim.keymap.set('n', 'bla', function()
  vim.notify('hello!')
end)
    ]]
    -- prepend those lines to the beginning of the file
    vim.api.nvim_buf_set_lines(0, 0, 0, false, vim.split(text, '\n'))
    vim.cmd.write()
    vim.cmd 'luafile %'
  end,
  ['[File] Save current buffer as temp'] = function()
    local ft = vim.api.nvim_get_option_value('filetype', { buf = 0 })
    if ft == '' then
      vim.ui.select(vim.fn.getcompletion('', 'filetype'), { prompt = 'Filetype❯ ' }, function(selected)
        if not selected then
          vim.notify('Canceled.', vim.log.levels.INFO, { title = 'Save as temp' })
          return
        end
        vim.cmd('set filetype=' .. selected)
        -- save with the filetype extension
        vim.cmd('write ' .. vim.fn.tempname() .. '.' .. selected)
        vim.cmd 'edit'
      end)
    else
      vim.cmd('write ' .. vim.fn.tempname() .. '.' .. ft)
      vim.cmd 'edit'
    end
  end,
  ['[Misc] Fix corrupted ShaDa file'] = function()
    local title = 'ShaDa'
    local dir, shada_file = shada_location()

    local removed_tmp = 0
    for _, path in ipairs(vim.fn.glob(dir .. '/*.tmp.*', false, true)) do
      if vim.fn.delete(path) == 0 then
        removed_tmp = removed_tmp + 1
      end
    end

    if vim.fn.filereadable(shada_file) ~= 1 then
      vim.cmd 'wshada'
      vim.notify(('Wrote new ShaDa file (none existed). Removed %d stale temp file(s).'):format(removed_tmp), vim.log.levels.INFO, { title = title })
      return
    end

    local backup = shada_file .. '.broken.' .. os.date '%Y%m%d-%H%M%S'
    if vim.fn.rename(shada_file, backup) ~= 0 then
      vim.notify('Could not move corrupt ShaDa file: ' .. shada_file, vim.log.levels.ERROR, { title = title })
      return
    end

    local ok = pcall(vim.cmd, 'silent! rshada! ' .. vim.fn.fnameescape(backup))
    vim.cmd 'wshada'

    local msg
    if ok then
      msg = ('Repaired ShaDa (salvaged what could be read). Backup: %s'):format(backup)
      if removed_tmp > 0 then
        msg = msg .. ('. Removed %d stale temp file(s).'):format(removed_tmp)
      end
      vim.notify(msg, vim.log.levels.INFO, { title = title })
    else
      msg = ('ShaDa reset (history lost). Corrupt backup: %s'):format(backup)
      if removed_tmp > 0 then
        msg = msg .. ('. Removed %d stale temp file(s).'):format(removed_tmp)
      end
      vim.notify(msg, vim.log.levels.WARN, { title = title })
    end
  end,
  ['[JSON] Sort keys under a path with jq'] = function()
    local title = 'Sort JSON'
    if vim.fn.executable 'jq' == 0 then
      vim.notify('jq not found in PATH.', vim.log.levels.WARN, { title = title })
      return
    end

    local bufnr = 0
    local src = table.concat(vim.api.nvim_buf_get_lines(bufnr, 0, -1, false), '\n')
    local enum = vim
      .system({
        'jq',
        '-c',
        'paths(type == "object" or type == "array") as $p | select((getpath($p) | length) > 1) | { p: $p, label: ("." + ($p | map(tostring) | join("."))) }',
      }, { stdin = src })
      :wait()
    if enum.code ~= 0 then
      vim.notify('Invalid JSON: ' .. (enum.stderr or ''), vim.log.levels.WARN, { title = title })
      return
    end

    local candidates = {}
    for line in vim.gsplit(enum.stdout, '\n', { trimempty = true }) do
      table.insert(candidates, vim.json.decode(line))
    end
    if #candidates == 0 then
      vim.notify('No container with multiple children to sort.', vim.log.levels.WARN, { title = title })
      return
    end

    vim.ui.select(candidates, {
      prompt = 'Sort under: ',
      format_item = function(item)
        return item.label
      end,
    }, function(choice)
      if not choice then
        return
      end
      local res = vim
        .system({
          'jq',
          '--argjson',
          'p',
          vim.json.encode(choice.p),
          'setpath($p; getpath($p) | if type == "object" then to_entries | sort_by(.key) | from_entries else sort end)',
        }, { stdin = src })
        :wait()
      if res.code ~= 0 then
        vim.notify('jq failed: ' .. (res.stderr or ''), vim.log.levels.WARN, { title = title })
        return
      end
      vim.api.nvim_buf_set_lines(bufnr, 0, -1, false, vim.split((res.stdout:gsub('\n$', '')), '\n'))
      vim.notify(('Sorted %s.'):format(choice.label), vim.log.levels.INFO, { title = title })
    end)
  end,
}
